version: "3"
services: 
  valheim: 
    image: insidus341/valheim-discord-bot:latest
    environment: 
      - DISCORD_TOKEN=
      - SERVER_IP=
      - SERVER_PORT=2457
      - SERVER_PASSWORD=
      - VALHEIM_PLUS=1