version: "2"
services: 
  valheim-bot: 
    container_name: valheim-server-bot
    image: insidus341/valheim-server-bot:latest
    restart: always
    env_file: 
     - .bot.env
    volumes:
      - ./discord_admin_users.txt:/app/discord_admin_users.txt
      - /var/run/docker.sock:/var/run/docker.sock
    
  valheim-statistics: 
    container_name: valheim-server-statistics
    image: insidus341/valheim-server-statistics:latest
    restart: always
    env_file: 
     - .stats.env
    depends_on:
      - "influxdb"
  
  influxdb:
    container_name: valheim-server-influxdb
    image: docker.io/influxdb:1.8.4
    restart: always
    env_file:
      - .influxdb.env
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    ports:
      - 8086:8086
