version: "2"
services: 
  valheim-bot: 
    container_name: valheim-server-bot
    image: insidus341/valheim-bot-statistics:latest
    restart: always
    env_file: 
     - .bot.env
    networks:
      sites:
        ipv4_address: 172.31.0.2
    
  valheim-statistics: 
    container_name: valheim-server-statistics
    image: insidus341/valheim-bot-statistics:latest
    restart: always
    env_file: 
     - .bot.env
    environment: 
      - STATISTICS=1
    networks:
      sites:
        ipv4_address: 172.31.0.4
  
  influxdb:
    container_name: valheim-bot-influxdb
    image: docker.io/influxdb:1.8.4
    restart: always
    env_file:
      - .influxdb.env
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    ports:
      - 8086:8086
    networks:
      sites:
        ipv4_address: 172.31.0.3

networks:
  sites:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/24
          gateway: 172.31.0.1