version: "2"
services: 
  valheim: 
    container_name: valheim-bot
    image: insidus341/valheim-discord-bot:latest
    env_file: 
     - .bot.env
     - .influxdb.env
    networks:
      sites:
        ipv4_address: 172.31.0.2
  
  influxdb:
    container_name: valheim-bot-influxdb
    image: docker.io/influxdb:1.8.4
    env_file:
      - .influxdb.env
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    ports:
      - 8086:8086
    networks:
      sites:
        ipv4_address: 172.31.0.3

networks:
  sites:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/24
          gateway: 172.31.0.1